# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f147c7b3-5ad1-420e-86af-a909ed28e61e";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/18DB-9B01";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/8a7ff726-63bd-4c8b-a895-54ded98c7605"; }
    ];

    #Mounting secondary drives, shared with the windows installation
    /*
  fileSystems."/run/media/johannes/Fast Auxillery Storage" =
    { device = "/dev/disk/by-uuid/A29E926B9E9237AD";
      fsType = "ntfs-3g";
      options = [ "rw" "uid=1000" "gid=100" "nofail" ];
    };
  fileSystems."/run/media/johannes/Windows11_System_Disk" =
    { device = "/dev/disk/by-uuid/80A8B4C6A8B4BBCA";
      fsType = "ntfs-3g";
      options = [ "rw" "uid=1000" "gid=100" "nofail" ];
    };
    */

    #Mouting the Unraid Server NFS Shares:
  #fileSystems."/mnt/personal_data" =
    #{ device = "192.168.0.202:/mnt/user/personal_data_johannes";
      #fsType = "nfs";
      #options = [
        #"x-systemd.automount"
        #"x-systemd.requires=network-online.target"
        #"x-systemd.after=network-online.target"
        #"nofail"
      #];
    #};
  fileSystems."/mnt/Johannes" =
    { device = "192.168.0.202:/mnt/user/Johannes";
      fsType = "nfs";
      options = [
        "x-systemd.automount"
        "x-systemd.requires=network-online.target"
        "x-systemd.after=network-online.target"
        "nofail"
      ];
    };
  fileSystems."/mnt/media" =
    { device = "192.168.0.202:/mnt/user/Media";
      fsType = "nfs";
      options = [
        #"x-systemd.automount"
        "x-systemd.requires=network-online.target"
        "x-systemd.after=network-online.target"
        "nofail"
      ];
    };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp7s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
